version: '3.8'

services:
  database:
    container_name: database
    build: ./database
    environment:
      - MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD
      - MONGO_DATABASE
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    networks:
      - services

networks:
  services:

volumes:
  database:
